package co.edu.uniquindio.proyecto.Modelo;

public enum Ciudad {
    ARMENIA,BARRANCABERMEJA,BARRANQUILLA,BOGOTA,BUCARAMANGA,
    BUGA,CALI,CATAGENA,CHIA,CUCUTA,DUITAMA,FLORENCIA,FUSAGASUGA,
    GIRARDOT,HONDA,IBAGUE,IPIALES,JAMUNDI,LETICIA,MANIZALES,MARIQUITA,
    MEDELLIN,MOMPOX,MONTERIA,MURILLO,NEIVA,PAMPLONA,PASTO,PEREIRA,
    POPAYAN,RIOHACHA,SAN_ANDRES,SAN_ANTERO,SANTA_MARATA,SANTAFE_ANTIOQUIA,
    SEVILLA,SICELEJO,SOGAMOSO,TABIO,TOCANCIPA,TOLU,TULUA,TUMACO,TUNJA,VALLEDUPAR,
    VILLAVICANCIO,YOPAL,ZIPAQUIRA
}
